INSERT INTO public.cities (image,city_name) VALUES
	 ('image1.png','Абаза'),
	 ('image2.png','Абакан'),
	 ('image3.jpeg','Абдулино'),
	 ('image4.png','Абинск'),
	 ('image5.png','Агидель'),
	 ('image6.png','Агрыз'),
	 ('image7.png','Адыгейск'),
	 ('image8.png','Азнакаево'),
	 ('image9.png','Азов'),
	 ('image10.png','Ак-Довурак');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image11.png','Аксай'),
	 ('image12.png','Алагир'),
	 ('image13.png','Алапаевск'),
	 ('image14.png','Алатырь'),
	 ('image15.png','Алдан'),
	 ('image16.gif','Алейск'),
	 ('image17.gif','Александров'),
	 ('image18.png','Александровск'),
	 ('image19.png','Александровск-Сахалинский'),
	 ('image20.png','Алексеевка');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image21.png','Алексин'),
	 ('image22.png','Алзамай'),
	 ('image23.png','Алупкане призн.'),
	 ('image24.png','Алуштане призн.'),
	 ('image25.gif','Альметьевск'),
	 ('image26.png','Амурск'),
	 ('image27.png','Анадырь'),
	 ('image28.png','Анапа'),
	 ('image29.png','Ангарск'),
	 ('image30.png','Андреаполь');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image31.png','Анжеро-Судженск'),
	 ('image32.gif','Анива'),
	 ('image33.png','Апатиты'),
	 ('image34.gif','Апрелевка'),
	 ('image35.png','Апшеронск'),
	 ('image36.png','Арамиль'),
	 ('image37.png','Аргун'),
	 ('image38.gif','Ардатов'),
	 ('image39.png','Ардон'),
	 ('image40.png','Арзамас');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image41.png','Аркадак'),
	 ('image42.jpeg','Армавир'),
	 ('image43.png','Армянскне призн.'),
	 ('image44.png','Арсеньев'),
	 ('image45.png','Арск'),
	 ('image46.png','Артём'),
	 ('image47.png','Артёмовск'),
	 ('image48.png','Артёмовский'),
	 ('image49.png','Архангельск'),
	 ('image50.png','Асбест');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image51.jpeg','Асино'),
	 ('image52.png','Астрахань'),
	 ('image53.jpeg','Аткарск'),
	 ('image54.gif','Ахтубинск'),
	 ('image55.png','Ачинск'),
	 ('image56.png','Аша'),
	 ('image57.png','Бабаево'),
	 ('image58.gif','Бабушкин'),
	 ('image59.png','Бавлы'),
	 ('image60.png','Багратионовск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image61.gif','Байкальск'),
	 ('image62.png','Баймак'),
	 ('image63.png','Бакал'),
	 ('image64.png','Баксан'),
	 ('image65.gif','Балабаново'),
	 ('image66.png','Балаково'),
	 ('image67.jpeg','Балахна'),
	 ('image68.png','Балашиха'),
	 ('image69.gif','Балашов'),
	 ('image70.png','Балей');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image71.png','Балтийск'),
	 ('image72.png','Барабинск'),
	 ('image73.jpeg','Барнаул'),
	 ('image74.gif','Барыш'),
	 ('image75.png','Батайск'),
	 ('image76.png','Бахчисарайне призн.'),
	 ('image77.png','Бежецк'),
	 ('image78.png','Белая Калитва'),
	 ('image79.png','Белая Холуница'),
	 ('image80.png','Белгород');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image81.png','Белебей'),
	 ('image82.png','Белёв'),
	 ('image83.png','Белинский'),
	 ('image84.png','Белово'),
	 ('image85.png','Белогорск'),
	 ('image86.png','Белогорскне призн.'),
	 ('image87.png','Белозерск'),
	 ('image88.png','Белокуриха'),
	 ('image89.png','Беломорск'),
	 ('image90.png','Белоозёрский');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image91.png','Белорецк'),
	 ('image92.png','Белореченск'),
	 ('image93.png','Белоусово'),
	 ('image94.png','Белоярский'),
	 ('image95.jpeg','Белый'),
	 ('image96.png','Бердск'),
	 ('image97.jpeg','Березники'),
	 ('image98.gif','Берёзовский'),
	 ('image99.png','Берёзовский'),
	 ('image100.png','Беслан');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image101.png','Бийск'),
	 ('image102.png','Бикин'),
	 ('image103.gif','Билибино'),
	 ('image104.png','Биробиджан'),
	 ('image105.png','Бирск'),
	 ('image106.png','Бирюсинск'),
	 ('image107.png','Бирюч'),
	 ('image108.png','Благовещенск'),
	 ('image109.png','Благовещенск'),
	 ('image110.png','Благодарный');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image111.gif','Бобров'),
	 ('image112.png','Богданович'),
	 ('image113.png','Богородицк'),
	 ('image114.png','Богородск'),
	 ('image115.gif','Боготол'),
	 ('image116.png','Богучар'),
	 ('image117.png','Бодайбо'),
	 ('image118.png','Бокситогорск'),
	 ('image119.gif','Болгар'),
	 ('image120.png','Бологое');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image121.png','Болотное'),
	 ('image122.png','Болохово'),
	 ('image123.png','Болхов'),
	 ('image124.png','Большой Камень'),
	 ('image125.png','Бор'),
	 ('image126.gif','Борзя'),
	 ('image127.png','Борисоглебск'),
	 ('image128.png','Боровичи'),
	 ('image129.png','Боровск'),
	 ('image130.png','Бородино');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image131.gif','Братск'),
	 ('image132.gif','Бронницы'),
	 ('image133.png','Брянск'),
	 ('image134.gif','Бугульма'),
	 ('image135.png','Бугуруслан'),
	 ('image136.png','Будённовск'),
	 ('image137.jpeg','Бузулук'),
	 ('image138.png','Буинск'),
	 ('image139.png','Буй'),
	 ('image140.png','Буйнакск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image141.gif','Бутурлиновка'),
	 ('image142.png','Валдай'),
	 ('image143.png','Валуйки'),
	 ('image144.png','Велиж'),
	 ('image145.png','Великие Луки'),
	 ('image146.png','Великий Новгород'),
	 ('image147.gif','Великий Устюг'),
	 ('image148.png','Вельск'),
	 ('image149.gif','Венёв'),
	 ('image150.png','Верещагино');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image151.png','Верея'),
	 ('image152.png','Верхнеуральск'),
	 ('image153.png','Верхний Тагил'),
	 ('image154.png','Верхний Уфалей'),
	 ('image155.png','Верхняя Пышма'),
	 ('image156.png','Верхняя Салда'),
	 ('image157.png','Верхняя Тура'),
	 ('image158.png','Верхотурье'),
	 ('image159.gif','Верхоянск'),
	 ('image160.png','Весьегонск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image161.png','Ветлуга'),
	 ('image162.png','Видное'),
	 ('image163.png','Вилюйск'),
	 ('image164.png','Вилючинск'),
	 ('image165.gif','Вихоревка'),
	 ('image166.png','Вичуга'),
	 ('image167.png','Владивосток'),
	 ('image168.png','Владикавказ'),
	 ('image169.gif','Владимир'),
	 ('image170.png','Волгоград');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image171.gif','Волгодонск'),
	 ('image172.png','Волгореченск'),
	 ('image173.png','Волжск'),
	 ('image174.png','Волжский'),
	 ('image175.png','Вологда'),
	 ('image176.png','Володарск'),
	 ('image177.png','Волоколамск'),
	 ('image178.png','Волосово'),
	 ('image179.png','Волхов'),
	 ('image180.png','Волчанск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image181.png','Вольск'),
	 ('image182.png','Воркута'),
	 ('image183.gif','Воронеж'),
	 ('image184.png','Ворсма'),
	 ('image185.png','Воскресенск'),
	 ('image186.png','Воткинск'),
	 ('image187.png','Всеволожск'),
	 ('image188.png','Вуктыл'),
	 ('image189.gif','Выборг'),
	 ('image190.png','Выкса');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image191.png','Высоковск'),
	 ('image192.gif','Высоцк'),
	 ('image193.png','Вытегра'),
	 ('image194.gif','Вышний Волочёк'),
	 ('image195.gif','Вяземский'),
	 ('image196.png','Вязники'),
	 ('image197.png','Вязьма'),
	 ('image198.png','Вятские Поляны'),
	 ('image199.png','Гаврилов Посад'),
	 ('image200.png','Гаврилов-Ям');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image201.png','Гагарин'),
	 ('image202.png','Гаджиево'),
	 ('image203.png','Гай'),
	 ('image204.png','Галич'),
	 ('image205.png','Гатчина'),
	 ('image206.png','Гвардейск'),
	 ('image207.png','Гдов'),
	 ('image208.png','Геленджик'),
	 ('image209.png','Георгиевск'),
	 ('image210.png','Глазов');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image211.png','Голицыно'),
	 ('image212.png','Горбатов'),
	 ('image213.png','Горно-Алтайск'),
	 ('image214.png','Горнозаводск'),
	 ('image215.png','Горняк'),
	 ('image216.png','Городец'),
	 ('image217.gif','Городище'),
	 ('image218.png','Городовиковск'),
	 ('image219.gif','Гороховец'),
	 ('image220.gif','Горячий Ключ');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image221.gif','Грайворон'),
	 ('image222.png','Гремячинск'),
	 ('image223.png','Грозный'),
	 ('image224.gif','Грязи'),
	 ('image225.png','Грязовец'),
	 ('image226.gif','Губаха'),
	 ('image227.gif','Губкин'),
	 ('image228.png','Губкинский'),
	 ('image229.png','Гудермес'),
	 ('image230.png','Гуково');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image231.png','Гулькевичи'),
	 ('image232.png','Гурьевск'),
	 ('image233.png','Гурьевск'),
	 ('image234.png','Гусев'),
	 ('image235.png','Гусиноозёрск'),
	 ('image236.png','Гусь-Хрустальный'),
	 ('image237.png','Давлеканово'),
	 ('image238.gif','Дагестанские Огни'),
	 ('image239.gif','Далматово'),
	 ('image240.png','Дальнегорск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image241.gif','Дальнереченск'),
	 ('image242.jpeg','Данилов'),
	 ('image243.png','Данков'),
	 ('image244.png','Дегтярск'),
	 ('image245.png','Дедовск'),
	 ('image246.png','Демидов'),
	 ('image247.png','Дербент'),
	 ('image248.png','Десногорск'),
	 ('image249.png','Джанкойне призн.'),
	 ('image250.png','Дзержинск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image251.png','Дзержинский'),
	 ('image252.png','Дивногорск'),
	 ('image253.png','Дигора'),
	 ('image254.png','Димитровград'),
	 ('image255.png','Дмитриев'),
	 ('image256.png','Дмитров'),
	 ('image257.png','Дмитровск'),
	 ('image258.png','Дно'),
	 ('image259.gif','Добрянка'),
	 ('image260.png','Долгопрудный');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image261.png','Долинск'),
	 ('image262.png','Домодедово'),
	 ('image263.png','Донецк'),
	 ('image264.gif','Донской'),
	 ('image265.png','Дорогобуж'),
	 ('image266.gif','Дрезна'),
	 ('image267.png','Дубна'),
	 ('image268.png','Дубовка'),
	 ('image269.png','Дудинка'),
	 ('image270.gif','Духовщина');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image271.png','Дюртюли'),
	 ('image272.gif','Дятьково'),
	 ('image273.png','Евпаторияне призн.'),
	 ('image274.gif','Егорьевск'),
	 ('image275.png','Ейск'),
	 ('image276.png','Екатеринбург'),
	 ('image277.png','Елабуга'),
	 ('image278.png','Елец'),
	 ('image279.png','Елизово'),
	 ('image280.png','Ельня');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image281.png','Еманжелинск'),
	 ('image282.png','Емва'),
	 ('image283.gif','Енисейск'),
	 ('image284.png','Ермолино'),
	 ('image285.png','Ершов'),
	 ('image286.png','Ессентуки'),
	 ('image287.jpeg','Ефремов'),
	 ('image288.png','Железноводск'),
	 ('image289.gif','Железногорск'),
	 ('image290.gif','Железногорск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image291.png','Железногорск-Илимский'),
	 ('image292.png','Жердевка'),
	 ('image293.png','Жигулёвск'),
	 ('image294.gif','Жиздра'),
	 ('image295.gif','Жирновск'),
	 ('image296.gif','Жуков'),
	 ('image297.png','Жуковка'),
	 ('image298.gif','Жуковский'),
	 ('image299.png','Завитинск'),
	 ('image300.jpeg','Заводоуковск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image301.gif','Заволжск'),
	 ('image302.png','Заволжье'),
	 ('image303.png','Задонск'),
	 ('image304.png','Заинск'),
	 ('image305.gif','Закаменск'),
	 ('image306.png','Заозёрный'),
	 ('image307.png','Заозёрск'),
	 ('image308.png','Западная Двина'),
	 ('image309.gif','Заполярный'),
	 ('image310.png','Зарайск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image311.png','Заречный'),
	 ('image312.gif','Заречный'),
	 ('image313.png','Заринск'),
	 ('image314.gif','Звенигово'),
	 ('image315.gif','Звенигород'),
	 ('image316.png','Зверево'),
	 ('image317.gif','Зеленогорск'),
	 ('image318.gif','Зеленоградск'),
	 ('image319.png','Зеленодольск'),
	 ('image320.png','Зеленокумск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image321.png','Зерноград'),
	 ('image322.png','Зея'),
	 ('image323.png','Зима'),
	 ('image324.gif','Златоуст'),
	 ('image325.png','Злынка'),
	 ('image326.png','Змеиногорск'),
	 ('image327.png','Знаменск'),
	 ('image328.png','Зубцов'),
	 ('image329.gif','Зуевка'),
	 ('image330.png','Ивангород');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image331.png','Иваново'),
	 ('image332.png','Ивантеевка'),
	 ('image333.png','Ивдель'),
	 ('image334.png','Игарка'),
	 ('image335.jpeg','Ижевск'),
	 ('image336.png','Избербаш'),
	 ('image337.png','Изобильный'),
	 ('image338.png','Иланский'),
	 ('image339.png','Инза'),
	 ('image340.png','Иннополис');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image341.png','Инсар'),
	 ('image342.png','Инта'),
	 ('image343.png','Ипатово'),
	 ('image344.png','Ирбит'),
	 ('image345.gif','Иркутск'),
	 ('image346.png','Исилькуль'),
	 ('image347.png','Искитим'),
	 ('image348.png','Истра'),
	 ('image349.gif','Ишим'),
	 ('image350.png','Ишимбай');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image351.png','Йошкар-Ола'),
	 ('image352.png','Кадников'),
	 ('image353.png','Казань'),
	 ('image354.png','Калач'),
	 ('image355.png','Калач-на-Дону'),
	 ('image356.png','Калачинск'),
	 ('image357.gif','Калининград'),
	 ('image358.png','Калининск'),
	 ('image359.png','Калтан'),
	 ('image360.png','Калуга');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image361.png','Калязин'),
	 ('image362.gif','Камбарка'),
	 ('image363.gif','Каменка'),
	 ('image364.gif','Каменногорск'),
	 ('image365.png','Каменск-Уральский'),
	 ('image366.png','Каменск-Шахтинский'),
	 ('image367.gif','Камень-на-Оби'),
	 ('image368.png','Камешково'),
	 ('image369.png','Камызяк'),
	 ('image370.png','Камышин');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image371.png','Камышлов'),
	 ('image372.gif','Канаш'),
	 ('image373.gif','Кандалакша'),
	 ('image374.png','Канск'),
	 ('image375.jpeg','Карабаново'),
	 ('image376.gif','Карабаш'),
	 ('image377.png','Карабулак'),
	 ('image378.png','Карасук'),
	 ('image379.png','Карачаевск'),
	 ('image380.png','Карачев');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image381.png','Каргат'),
	 ('image382.jpeg','Каргополь'),
	 ('image383.png','Карпинск'),
	 ('image384.png','Карталы'),
	 ('image385.png','Касимов'),
	 ('image386.png','Касли'),
	 ('image387.png','Каспийск'),
	 ('image388.png','Катав-Ивановск'),
	 ('image389.gif','Катайск'),
	 ('image390.png','Качканар');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image391.png','Кашин'),
	 ('image392.png','Кашира'),
	 ('image393.gif','Кедровый'),
	 ('image394.png','Кемерово'),
	 ('image395.png','Кемь'),
	 ('image396.png','Керчьне призн.'),
	 ('image397.gif','Кизел'),
	 ('image398.png','Кизилюрт'),
	 ('image399.png','Кизляр'),
	 ('image400.png','Кимовск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image401.png','Кимры'),
	 ('image402.png','Кингисепп'),
	 ('image403.png','Кинель'),
	 ('image404.png','Кинешма'),
	 ('image405.gif','Киреевск'),
	 ('image406.png','Киренск'),
	 ('image407.gif','Киржач'),
	 ('image408.png','Кириллов'),
	 ('image409.png','Кириши'),
	 ('image410.png','Киров');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image411.png','Киров'),
	 ('image412.png','Кировград'),
	 ('image413.png','Кирово-Чепецк'),
	 ('image414.png','Кировск'),
	 ('image415.gif','Кировск'),
	 ('image416.png','Кирс'),
	 ('image417.png','Кирсанов'),
	 ('image418.png','Киселёвск'),
	 ('image419.png','Кисловодск'),
	 ('image420.png','Клин');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image421.png','Клинцы'),
	 ('image422.png','Княгинино'),
	 ('image423.gif','Ковдор'),
	 ('image424.png','Ковров'),
	 ('image425.png','Ковылкино'),
	 ('image426.png','Когалым'),
	 ('image427.png','Кодинск'),
	 ('image428.png','Козельск'),
	 ('image429.png','Козловка'),
	 ('image430.png','Козьмодемьянск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image431.png','Кола'),
	 ('image432.gif','Кологрив'),
	 ('image433.png','Коломна'),
	 ('image434.png','Колпашево'),
	 ('image435.png','Кольчугино'),
	 ('image436.png','Коммунар'),
	 ('image437.png','Комсомольск'),
	 ('image438.png','Комсомольск-на-Амуре'),
	 ('image439.png','Конаково'),
	 ('image440.png','Кондопога');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image441.png','Кондрово'),
	 ('image442.png','Константиновск'),
	 ('image443.gif','Копейск'),
	 ('image444.png','Кораблино'),
	 ('image445.png','Кореновск'),
	 ('image446.gif','Коркино'),
	 ('image447.png','Королёв'),
	 ('image448.png','Короча'),
	 ('image449.gif','Корсаков'),
	 ('image450.png','Коряжма');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image451.png','Костерёво'),
	 ('image452.gif','Костомукша'),
	 ('image453.png','Кострома'),
	 ('image454.png','Котельники'),
	 ('image455.gif','Котельниково'),
	 ('image456.png','Котельнич'),
	 ('image457.png','Котлас'),
	 ('image458.png','Котово'),
	 ('image459.gif','Котовск'),
	 ('image460.jpeg','Кохма');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image461.png','Красавино'),
	 ('image462.gif','Красноармейск'),
	 ('image463.png','Красноармейск'),
	 ('image464.png','Красновишерск'),
	 ('image465.png','Красногорск'),
	 ('image466.png','Краснодар'),
	 ('image467.png','Краснозаводск'),
	 ('image468.png','Краснознаменск'),
	 ('image469.png','Краснознаменск'),
	 ('image470.png','Краснокаменск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image471.png','Краснокамск'),
	 ('image472.png','Красноперекопскне призн.'),
	 ('image473.png','Краснослободск'),
	 ('image474.png','Краснослободск'),
	 ('image475.png','Краснотурьинск'),
	 ('image476.png','Красноуральск'),
	 ('image477.gif','Красноуфимск'),
	 ('image478.png','Красноярск'),
	 ('image479.gif','Красный Кут'),
	 ('image480.gif','Красный Сулин');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image481.png','Красный Холм'),
	 ('image482.png','Кремёнки'),
	 ('image483.gif','Кропоткин'),
	 ('image484.gif','Крымск'),
	 ('image485.png','Кстово'),
	 ('image486.png','Кубинка'),
	 ('image487.png','Кувандык'),
	 ('image488.png','Кувшиново'),
	 ('image489.png','Кудрово'),
	 ('image490.png','Кудымкар');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image491.png','Кузнецк'),
	 ('image492.png','Куйбышев'),
	 ('image493.png','Кукмор'),
	 ('image494.png','Кулебаки'),
	 ('image495.gif','Кумертау'),
	 ('image496.png','Кунгур'),
	 ('image497.png','Купино'),
	 ('image498.png','Курган'),
	 ('image499.png','Курганинск'),
	 ('image500.gif','Курильск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image501.png','Курлово'),
	 ('image502.png','Куровское'),
	 ('image503.png','Курск'),
	 ('image504.png','Куртамыш'),
	 ('image505.gif','Курчалой'),
	 ('image506.png','Курчатов'),
	 ('image507.png','Куса'),
	 ('image508.gif','Кушва'),
	 ('image509.gif','Кызыл'),
	 ('image510.gif','Кыштым');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image511.png','Кяхта'),
	 ('image512.png','Лабинск'),
	 ('image513.png','Лабытнанги'),
	 ('image514.png','Лагань'),
	 ('image515.gif','Ладушкин'),
	 ('image516.png','Лаишево'),
	 ('image517.png','Лакинск'),
	 ('image518.gif','Лангепас'),
	 ('image519.png','Лахденпохья'),
	 ('image520.png','Лебедянь');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image521.png','Лениногорск'),
	 ('image522.png','Ленинск'),
	 ('image523.png','Ленинск-Кузнецкий'),
	 ('image524.png','Ленск'),
	 ('image525.png','Лермонтов'),
	 ('image526.png','Лесной'),
	 ('image527.png','Лесозаводск'),
	 ('image528.png','Лесосибирск'),
	 ('image529.png','Ливны'),
	 ('image530.png','Ликино-Дулёво');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image531.gif','Липецк'),
	 ('image532.png','Липки'),
	 ('image533.gif','Лиски'),
	 ('image534.png','Лихославль'),
	 ('image535.gif','Лобня'),
	 ('image536.png','Лодейное Поле'),
	 ('image537.png','Лосино-Петровский'),
	 ('image538.png','Луга'),
	 ('image539.png','Луза'),
	 ('image540.gif','Лукоянов');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image541.png','Луховицы'),
	 ('image542.png','Лысково'),
	 ('image543.jpeg','Лысьва'),
	 ('image544.png','Лыткарино'),
	 ('image545.png','Льгов'),
	 ('image546.png','Любань'),
	 ('image547.png','Люберцы'),
	 ('image548.png','Любим'),
	 ('image549.png','Людиново'),
	 ('image550.png','Лянтор');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image551.png','Магадан'),
	 ('image552.png','Магас'),
	 ('image553.png','Магнитогорск'),
	 ('image554.png','Майкоп'),
	 ('image555.png','Майский'),
	 ('image556.png','Макаров'),
	 ('image557.png','Макарьев'),
	 ('image558.png','Макушино'),
	 ('image559.gif','Малая Вишера'),
	 ('image560.gif','Малгобек');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image561.png','Малмыж'),
	 ('image562.png','Малоархангельск'),
	 ('image563.png','Малоярославец'),
	 ('image564.gif','Мамадыш'),
	 ('image565.gif','Мамоново'),
	 ('image566.png','Мантурово'),
	 ('image567.png','Мариинск'),
	 ('image568.png','Мариинский Посад'),
	 ('image569.png','Маркс'),
	 ('image570.gif','Махачкала');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image571.png','Мглин'),
	 ('image572.png','Мегион'),
	 ('image573.png','Медвежьегорск'),
	 ('image574.png','Медногорск'),
	 ('image575.png','Медынь'),
	 ('image576.png','Межгорье'),
	 ('image577.png','Междуреченск'),
	 ('image578.png','Мезень'),
	 ('image579.png','Меленки'),
	 ('image580.png','Мелеуз');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image581.png','Менделеевск'),
	 ('image582.gif','Мензелинск'),
	 ('image583.png','Мещовск'),
	 ('image584.png','Миасс'),
	 ('image585.png','Микунь'),
	 ('image586.png','Миллерово'),
	 ('image587.png','Минеральные Воды'),
	 ('image588.gif','Минусинск'),
	 ('image589.png','Миньяр'),
	 ('image590.png','Мирный');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image591.png','Мирный'),
	 ('image592.png','Михайлов'),
	 ('image593.gif','Михайловка'),
	 ('image594.png','Михайловск'),
	 ('image595.png','Михайловск'),
	 ('image596.png','Мичуринск'),
	 ('image597.gif','Могоча'),
	 ('image598.png','Можайск'),
	 ('image599.png','Можга'),
	 ('image600.png','Моздок');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image601.png','Мончегорск'),
	 ('image602.png','Морозовск'),
	 ('image603.png','Моршанск'),
	 ('image604.gif','Мосальск'),
	 ('image605.png','Москва'),
	 ('image606.gif','Муравленко'),
	 ('image607.png','Мураши'),
	 ('image608.jpeg','Мурино'),
	 ('image609.gif','Мурманск'),
	 ('image610.png','Муром');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image611.png','Мценск'),
	 ('image612.png','Мыски'),
	 ('image613.png','Мытищи'),
	 ('image614.png','Мышкин'),
	 ('image615.png','Набережные Челны'),
	 ('image616.png','Навашино'),
	 ('image617.png','Наволоки'),
	 ('image618.png','Надым'),
	 ('image619.png','Назарово'),
	 ('image620.png','Назрань');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image621.jpeg','Называевск'),
	 ('image622.png','Нальчик'),
	 ('image623.png','Нариманов'),
	 ('image624.png','Наро-Фоминск'),
	 ('image625.png','Нарткала'),
	 ('image626.png','Нарьян-Мар'),
	 ('image627.png','Находка'),
	 ('image628.png','Невель'),
	 ('image629.jpeg','Невельск'),
	 ('image630.png','Невинномысск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image631.png','Невьянск'),
	 ('image632.png','Нелидово'),
	 ('image633.png','Неман'),
	 ('image634.png','Нерехта'),
	 ('image635.png','Нерчинск'),
	 ('image636.png','Нерюнгри'),
	 ('image637.png','Нестеров'),
	 ('image638.png','Нефтегорск'),
	 ('image639.png','Нефтекамск'),
	 ('image640.gif','Нефтекумск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image641.png','Нефтеюганск'),
	 ('image642.gif','Нея'),
	 ('image643.png','Нижневартовск'),
	 ('image644.png','Нижнекамск'),
	 ('image645.png','Нижнеудинск'),
	 ('image646.gif','Нижние Серги'),
	 ('image647.png','Нижний Ломов'),
	 ('image648.png','Нижний Новгород'),
	 ('image649.png','Нижний Тагил'),
	 ('image650.gif','Нижняя Салда');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image651.png','Нижняя Тура'),
	 ('image652.png','Николаевск'),
	 ('image653.png','Николаевск-на-Амуре'),
	 ('image654.gif','Никольск'),
	 ('image655.png','Никольск'),
	 ('image656.png','Никольское'),
	 ('image657.gif','Новая Ладога'),
	 ('image658.png','Новая Ляля'),
	 ('image659.png','Новоалександровск'),
	 ('image660.png','Новоалтайск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image661.png','Новоаннинский'),
	 ('image662.gif','Нововоронеж'),
	 ('image663.gif','Новодвинск'),
	 ('image664.png','Новозыбков'),
	 ('image665.png','Новокубанск'),
	 ('image666.png','Новокузнецк'),
	 ('image667.png','Новокуйбышевск'),
	 ('image668.png','Новомичуринск'),
	 ('image669.png','Новомосковск'),
	 ('image670.gif','Новопавловск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image671.png','Новоржев'),
	 ('image672.png','Новороссийск'),
	 ('image673.gif','Новосибирск'),
	 ('image674.png','Новосиль'),
	 ('image675.gif','Новосокольники'),
	 ('image676.jpeg','Новотроицк'),
	 ('image677.png','Новоузенск'),
	 ('image678.png','Новоульяновск'),
	 ('image679.png','Новоуральск'),
	 ('image680.png','Новохопёрск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image681.gif','Новочебоксарск'),
	 ('image682.gif','Новочеркасск'),
	 ('image683.gif','Новошахтинск'),
	 ('image684.png','Новый Оскол'),
	 ('image685.png','Новый Уренгой'),
	 ('image686.png','Ногинск'),
	 ('image687.png','Нолинск'),
	 ('image688.png','Норильск'),
	 ('image689.png','Ноябрьск'),
	 ('image690.gif','Нурлат');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image691.png','Нытва'),
	 ('image692.png','Нюрба'),
	 ('image693.png','Нягань'),
	 ('image694.png','Нязепетровск'),
	 ('image695.gif','Няндома'),
	 ('image696.png','Облучье'),
	 ('image697.png','Обнинск'),
	 ('image698.png','Обоянь'),
	 ('image699.png','Обь'),
	 ('image700.png','Одинцово');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image701.gif','Озёрск'),
	 ('image702.gif','Озёрск'),
	 ('image703.gif','Озёры'),
	 ('image704.png','Октябрьск'),
	 ('image705.png','Октябрьский'),
	 ('image706.png','Окуловка'),
	 ('image707.png','Олёкминск'),
	 ('image708.png','Оленегорск'),
	 ('image709.png','Олонец'),
	 ('image710.png','Омск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image711.png','Омутнинск'),
	 ('image712.gif','Онега'),
	 ('image713.png','Опочка'),
	 ('image714.png','Орёл'),
	 ('image715.png','Оренбург'),
	 ('image716.png','Орехово-Зуево'),
	 ('image717.gif','Орлов'),
	 ('image718.gif','Орск'),
	 ('image719.png','Оса'),
	 ('image720.gif','Осинники');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image721.png','Осташков'),
	 ('image722.png','Остров'),
	 ('image723.png','Островной'),
	 ('image724.png','Острогожск'),
	 ('image725.png','Отрадное'),
	 ('image726.png','Отрадный'),
	 ('image727.png','Оха'),
	 ('image728.png','Оханск'),
	 ('image729.jpeg','Очёр'),
	 ('image730.gif','Павлово');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image731.gif','Павловск'),
	 ('image732.png','Павловский Посад'),
	 ('image733.png','Палласовка'),
	 ('image734.png','Партизанск'),
	 ('image735.gif','Певек'),
	 ('image736.gif','Пенза'),
	 ('image737.gif','Первомайск'),
	 ('image738.png','Первоуральск'),
	 ('image739.png','Перевоз'),
	 ('image740.png','Пересвет');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image741.png','Переславль-Залесский'),
	 ('image742.gif','Пермь'),
	 ('image743.jpeg','Пестово'),
	 ('image744.png','Петров Вал'),
	 ('image745.gif','Петровск'),
	 ('image746.png','Петровск-Забайкальский'),
	 ('image747.gif','Петрозаводск'),
	 ('image748.png','Петропавловск-Камчатский'),
	 ('image749.png','Петухово'),
	 ('image750.png','Петушки');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image751.gif','Печора'),
	 ('image752.png','Печоры'),
	 ('image753.png','Пикалёво'),
	 ('image754.gif','Пионерский'),
	 ('image755.gif','Питкяранта'),
	 ('image756.png','Плавск'),
	 ('image757.jpeg','Пласт'),
	 ('image758.gif','Плёс'),
	 ('image759.gif','Поворино'),
	 ('image760.png','Подольск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image761.png','Подпорожье'),
	 ('image762.png','Покачи'),
	 ('image763.jpeg','Покров'),
	 ('image764.png','Покровск'),
	 ('image765.png','Полевской'),
	 ('image766.png','Полесск'),
	 ('image767.png','Полысаево'),
	 ('image768.png','Полярные Зори'),
	 ('image769.gif','Полярный'),
	 ('image770.png','Поронайск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image771.png','Порхов'),
	 ('image772.gif','Похвистнево'),
	 ('image773.png','Почеп'),
	 ('image774.gif','Починок'),
	 ('image775.png','Пошехонье'),
	 ('image776.png','Правдинск'),
	 ('image777.png','Приволжск'),
	 ('image778.jpeg','Приморск'),
	 ('image779.png','Приморск'),
	 ('image780.gif','Приморско-Ахтарск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image781.gif','Приозерск'),
	 ('image782.png','Прокопьевск'),
	 ('image783.png','Пролетарск'),
	 ('image784.png','Протвино'),
	 ('image785.gif','Прохладный'),
	 ('image786.png','Псков'),
	 ('image787.gif','Пугачёв'),
	 ('image788.png','Пудож'),
	 ('image789.png','Пустошка'),
	 ('image790.png','Пучеж');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image791.png','Пушкино'),
	 ('image792.png','Пущино'),
	 ('image793.png','Пыталово'),
	 ('image794.png','Пыть-Ях'),
	 ('image795.png','Пятигорск'),
	 ('image796.png','Радужный'),
	 ('image797.gif','Радужный'),
	 ('image798.png','Райчихинск'),
	 ('image799.png','Раменское'),
	 ('image800.png','Рассказово');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image801.png','Ревда'),
	 ('image802.png','Реж'),
	 ('image803.png','Реутов'),
	 ('image804.png','Ржев'),
	 ('image805.png','Родники'),
	 ('image806.png','Рославль'),
	 ('image807.png','Россошь'),
	 ('image808.png','Ростов-на-Дону'),
	 ('image809.png','Ростов'),
	 ('image810.png','Рошаль');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image811.png','Ртищево'),
	 ('image812.png','Рубцовск'),
	 ('image813.png','Рудня'),
	 ('image814.gif','Руза'),
	 ('image815.gif','Рузаевка'),
	 ('image816.png','Рыбинск'),
	 ('image817.png','Рыбное'),
	 ('image818.png','Рыльск'),
	 ('image819.png','Ряжск'),
	 ('image820.png','Рязань');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image821.gif','Сакине призн.'),
	 ('image822.png','Салават'),
	 ('image823.png','Салаир'),
	 ('image824.png','Салехард'),
	 ('image825.png','Сальск'),
	 ('image826.gif','Самара'),
	 ('image827.png','Санкт-Петербург'),
	 ('image828.png','Саранск'),
	 ('image829.png','Сарапул'),
	 ('image830.png','Саратов');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image831.gif','Саров'),
	 ('image832.gif','Сасово'),
	 ('image833.png','Сатка'),
	 ('image834.png','Сафоново'),
	 ('image835.gif','Саяногорск'),
	 ('image836.png','Саянск'),
	 ('image837.png','Светлогорск'),
	 ('image838.gif','Светлоград'),
	 ('image839.png','Светлый'),
	 ('image840.png','Светогорск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image841.png','Свирск'),
	 ('image842.png','Свободный'),
	 ('image843.png','Себеж'),
	 ('image844.png','Севастопольне призн.'),
	 ('image845.png','Северо-Курильск'),
	 ('image846.png','Северобайкальск'),
	 ('image847.gif','Северодвинск'),
	 ('image848.png','Североморск'),
	 ('image849.png','Североуральск'),
	 ('image850.png','Северск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image851.png','Севск'),
	 ('image852.png','Сегежа'),
	 ('image853.png','Сельцо'),
	 ('image854.jpeg','Семёнов'),
	 ('image855.png','Семикаракорск'),
	 ('image856.png','Семилуки'),
	 ('image857.png','Сенгилей'),
	 ('image858.gif','Серафимович'),
	 ('image859.png','Сергач'),
	 ('image860.png','Сергиев Посад');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image861.gif','Сердобск'),
	 ('image862.png','Серов'),
	 ('image863.png','Серпухов'),
	 ('image864.png','Сертолово'),
	 ('image865.png','Сибай'),
	 ('image866.gif','Сим'),
	 ('image867.png','Симферопольне призн.'),
	 ('image868.png','Сковородино'),
	 ('image869.png','Скопин'),
	 ('image870.png','Славгород');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image871.gif','Славск'),
	 ('image872.png','Славянск-на-Кубани'),
	 ('image873.gif','Сланцы'),
	 ('image874.png','Слободской'),
	 ('image875.jpeg','Слюдянка'),
	 ('image876.png','Смоленск'),
	 ('image877.png','Снежинск'),
	 ('image878.png','Снежногорск'),
	 ('image879.png','Собинка'),
	 ('image880.gif','Советск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image881.png','Советск'),
	 ('image882.png','Советск'),
	 ('image883.png','Советская Гавань'),
	 ('image884.png','Советский'),
	 ('image885.png','Сокол'),
	 ('image886.png','Солигалич'),
	 ('image887.png','Соликамск'),
	 ('image888.gif','Солнечногорск'),
	 ('image889.png','Соль-Илецк'),
	 ('image890.png','Сольвычегодск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image891.png','Сольцы'),
	 ('image892.gif','Сорочинск'),
	 ('image893.png','Сорск'),
	 ('image894.png','Сортавала'),
	 ('image895.png','Сосенский'),
	 ('image896.png','Сосновка'),
	 ('image897.gif','Сосновоборск'),
	 ('image898.gif','Сосновый Бор'),
	 ('image899.gif','Сосногорск'),
	 ('image900.png','Сочи');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image901.png','Спас-Деменск'),
	 ('image902.png','Спас-Клепики'),
	 ('image903.png','Спасск'),
	 ('image904.gif','Спасск-Дальний'),
	 ('image905.png','Спасск-Рязанский'),
	 ('image906.png','Среднеколымск'),
	 ('image907.png','Среднеуральск'),
	 ('image908.gif','Сретенск'),
	 ('image909.gif','Ставрополь'),
	 ('image910.png','Старая Купавна');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image911.png','Старая Русса'),
	 ('image912.png','Старица'),
	 ('image913.png','Стародуб'),
	 ('image914.gif','Старый Крымне призн.'),
	 ('image915.gif','Старый Оскол'),
	 ('image916.png','Стерлитамак'),
	 ('image917.png','Стрежевой'),
	 ('image918.jpeg','Строитель'),
	 ('image919.png','Струнино'),
	 ('image920.png','Ступино');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image921.png','Суворов'),
	 ('image922.png','Судакне призн.'),
	 ('image923.gif','Суджа'),
	 ('image924.png','Судогда'),
	 ('image925.png','Суздаль'),
	 ('image926.gif','Сунжа'),
	 ('image927.gif','Суоярви'),
	 ('image928.png','Сураж'),
	 ('image929.gif','Сургут'),
	 ('image930.png','Суровикино');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image931.png','Сурск'),
	 ('image932.gif','Сусуман'),
	 ('image933.gif','Сухиничи'),
	 ('image934.png','Сухой Лог'),
	 ('image935.png','Сызрань'),
	 ('image936.png','Сыктывкар'),
	 ('image937.png','Сысерть'),
	 ('image938.png','Сычёвка'),
	 ('image939.png','Сясьстрой'),
	 ('image940.png','Тавда');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image941.gif','Таганрог'),
	 ('image942.png','Тайга'),
	 ('image943.png','Тайшет'),
	 ('image944.png','Талдом'),
	 ('image945.png','Талица'),
	 ('image946.gif','Тамбов'),
	 ('image947.png','Тара'),
	 ('image948.png','Тарко-Сале'),
	 ('image949.png','Таруса'),
	 ('image950.png','Татарск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image951.png','Таштагол'),
	 ('image952.png','Тверь'),
	 ('image953.png','Теберда'),
	 ('image954.png','Тейково'),
	 ('image955.png','Темников'),
	 ('image956.png','Темрюк'),
	 ('image957.png','Терек'),
	 ('image958.png','Тетюши'),
	 ('image959.png','Тимашёвск'),
	 ('image960.gif','Тихвин');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image961.gif','Тихорецк'),
	 ('image962.png','Тобольск'),
	 ('image963.png','Тогучин'),
	 ('image964.png','Тольятти'),
	 ('image965.png','Томари'),
	 ('image966.png','Томмот'),
	 ('image967.gif','Томск'),
	 ('image968.png','Топки'),
	 ('image969.gif','Торжок'),
	 ('image970.gif','Торопец');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image971.png','Тосно'),
	 ('image972.png','Тотьма'),
	 ('image973.png','Трёхгорный'),
	 ('image974.png','Троицк'),
	 ('image975.gif','Трубчевск'),
	 ('image976.gif','Туапсе'),
	 ('image977.png','Туймазы'),
	 ('image978.png','Тула'),
	 ('image979.png','Тулун'),
	 ('image980.png','Туран');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image981.png','Туринск'),
	 ('image982.gif','Тутаев'),
	 ('image983.png','Тында'),
	 ('image984.png','Тырныауз'),
	 ('image985.png','Тюкалинск'),
	 ('image986.jpeg','Тюмень'),
	 ('image987.png','Уварово'),
	 ('image988.png','Углегорск'),
	 ('image989.png','Углич'),
	 ('image990.gif','Удачный');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image991.png','Удомля'),
	 ('image992.png','Ужур'),
	 ('image993.png','Узловая'),
	 ('image994.png','Улан-Удэ'),
	 ('image995.png','Ульяновск'),
	 ('image996.png','Унеча'),
	 ('image997.png','Урай'),
	 ('image998.png','Урень'),
	 ('image999.gif','Уржум'),
	 ('image1000.png','Урус-Мартан');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image1001.png','Урюпинск'),
	 ('image1002.gif','Усинск'),
	 ('image1003.png','Усмань'),
	 ('image1004.png','Усолье-Сибирское'),
	 ('image1005.png','Усолье'),
	 ('image1006.png','Уссурийск'),
	 ('image1007.png','Усть-Джегута'),
	 ('image1008.png','Усть-Илимск'),
	 ('image1009.jpeg','Усть-Катав'),
	 ('image1010.png','Усть-Кут');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image1011.png','Усть-Лабинск'),
	 ('image1012.png','Устюжна'),
	 ('image1013.png','Уфа'),
	 ('image1014.png','Ухта'),
	 ('image1015.png','Учалы'),
	 ('image1016.png','Уяр'),
	 ('image1017.png','Фатеж'),
	 ('image1018.png','Феодосияне призн.'),
	 ('image1019.png','Фокино'),
	 ('image1020.png','Фокино');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image1021.png','Фролово'),
	 ('image1022.gif','Фрязино'),
	 ('image1023.png','Фурманов'),
	 ('image1024.png','Хабаровск'),
	 ('image1025.gif','Хадыженск'),
	 ('image1026.png','Ханты-Мансийск'),
	 ('image1027.gif','Харабали'),
	 ('image1028.png','Харовск'),
	 ('image1029.png','Хасавюрт'),
	 ('image1030.gif','Хвалынск');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image1031.png','Хилок'),
	 ('image1032.png','Химки'),
	 ('image1033.png','Холм'),
	 ('image1034.png','Холмск'),
	 ('image1035.png','Хотьково'),
	 ('image1036.png','Цивильск'),
	 ('image1037.png','Цимлянск'),
	 ('image1038.gif','Циолковский'),
	 ('image1039.png','Чадан'),
	 ('image1040.png','Чайковский');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image1041.gif','Чапаевск'),
	 ('image1042.png','Чаплыгин'),
	 ('image1043.png','Чебаркуль'),
	 ('image1044.png','Чебоксары'),
	 ('image1045.png','Чегем'),
	 ('image1046.gif','Чекалин'),
	 ('image1047.png','Челябинск'),
	 ('image1048.png','Чердынь'),
	 ('image1049.png','Черемхово'),
	 ('image1050.png','Черепаново');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image1051.png','Череповец'),
	 ('image1052.png','Черкесск'),
	 ('image1053.jpeg','Чёрмоз'),
	 ('image1054.png','Черноголовка'),
	 ('image1055.png','Черногорск'),
	 ('image1056.jpeg','Чернушка'),
	 ('image1057.png','Черняховск'),
	 ('image1058.png','Чехов'),
	 ('image1059.png','Чистополь'),
	 ('image1060.png','Чита');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image1061.png','Чкаловск'),
	 ('image1062.gif','Чудово'),
	 ('image1063.gif','Чулым'),
	 ('image1064.png','Чусовой'),
	 ('image1065.png','Чухлома'),
	 ('image1066.png','Шагонар'),
	 ('image1067.png','Шадринск'),
	 ('image1068.png','Шали'),
	 ('image1069.png','Шарыпово'),
	 ('image1070.png','Шарья');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image1071.gif','Шатура'),
	 ('image1072.png','Шахты'),
	 ('image1073.gif','Шахунья'),
	 ('image1074.jpeg','Шацк'),
	 ('image1075.png','Шебекино'),
	 ('image1076.gif','Шелехов'),
	 ('image1077.png','Шенкурск'),
	 ('image1078.png','Шилка'),
	 ('image1079.png','Шимановск'),
	 ('image1080.png','Шиханы');
INSERT INTO public.cities (image,city_name) VALUES
	 ('image1081.png','Шлиссельбург'),
	 ('image1082.png','Шумерля'),
	 ('image1083.gif','Шумиха'),
	 ('image1084.png','Шуя');
